---
name: BAP Docker Image on Tag

on:
  push:
    tags:
      - 'invch-[0-9]+.[0-9]+.[0-9]+'

jobs:
  build_and_push:
    uses: dBildungsplattform/dbp-github-workflows/.github/workflows/image-publish-trivy.yaml@7
    permissions:
      packages: write
      contents: read
      security-events: write
    with:
      image_name: invch
      container_registry: dockerhub
      dockerhub_repository_owner: "schulcloudci"
      add_latest_tag: true
      image_tag_generation: "mmp_git_tag,mm_git_tag"
      context: .
      run_trivy_scan: true
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
