name: On push to branch release chart 
on:
  push:
    branches-ignore:
      - 'main'
    paths:
      - 'charts/invch/**'
      - '.github/workflows/**'

concurrency:
  group: invch-chart
  cancel-in-progress: true

jobs:
  scan:
    uses: dBildungsplattform/dbp-github-workflows/.github/workflows/check-helm-kics.yaml@7
    permissions:
      contents: read
  release_helm:
    uses: dBildungsplattform/dbp-github-workflows/.github/workflows/chart-release.yaml@7
    secrets: inherit
    with:
      chart_path: charts
      chart_name: invch
      helm_chart_version_generation: ticket_from_branch_timestamp
      image_tag_generation: chart_yaml