---
name: invch Docker Image on Push to GHCR

on:
  push:
    branches-ignore:
      - main
    paths:
      - 'src/**'
      - 'requirements.txt'
      - 'Dockerfile'
  workflow_dispatch:

concurrency:
  group: invch-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_and_push:
    permissions:
      packages: write
      security-events: write
      contents: read
    uses: dBildungsplattform/dbp-github-workflows/.github/workflows/image-publish-trivy.yaml@7.0.0
    with:
      image_name: "invch"
      container_registry: "ghcr.io"
      add_latest_tag: false
      image_tag_generation: "ticket_from_branch"
      run_trivy_scan: true
